### ISSUE TITLE
Questions about the rules of the competition

### ISSUE THREAD

**Issue by hyunseoki** [cwwang1979/CL_detection2023_reference_docker#1]
Thank you for holding a good competition.
I have a few questions about the rules of the competition.

1. If I submit a Docker Image, it is my understanding that it will be used for inference in a cloud environment. What is the maximum GPU capacity that I can use?

2. Can I use pre-trained models in the competition?

Thank you

**Comment by cwwang1979** [comment]
Dear @hyunseoki 

Thank you for the questions.

**Q: If I submit a Docker Image, it is my understanding that it will be used for inference in a cloud environment. What is the maximum GPU capacity that I can use?**
A: According to the supporting officer of the grand challenge platform, "we run the algorithms with either 16GB or 32 GB memory, depending on what the user specifies in their algorithm setttings. The AWS instance types we use are then either ml.g4dn.xlarge or ml.g4dn.2xlarge. "

**Q: Can I use pre-trained models in the competition?**
A: Pre-trained models are allowed to build your algorithm model. However, please be reminded that you have to describe and explain your training strategy and your landmark detection algorithm by sending  a paper submission* in the LNCS Springer format (with 4 pages) along with your algorithm container submission for testing phase.

Best regards,

CL-detection challenge 2023 staff.
